module.exports = {
	login: 'infrony',
	id: 1005749,
	node_id: 'MDQ6VXNlcjEwMDU3NDk=',
	avatar_url: 'https://avatars2.githubusercontent.com/u/1005749?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/infrony',
	html_url: 'https://github.com/infrony',
	followers_url: 'https://api.github.com/users/infrony/followers',
	following_url: 'https://api.github.com/users/infrony/following{/other_user}',
	gists_url: 'https://api.github.com/users/infrony/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/infrony/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/infrony/subscriptions',
	organizations_url: 'https://api.github.com/users/infrony/orgs',
	repos_url: 'https://api.github.com/users/infrony/repos',
	events_url: 'https://api.github.com/users/infrony/events{/privacy}',
	received_events_url: 'https://api.github.com/users/infrony/received_events',
	type: 'User',
	site_admin: false,
	name: 'Rodney Guillen',
	company: '@infrony',
	blog: 'http://infrony.net',
	location: 'Panama',
	email: null,
	hireable: true,
	bio:
		'My name is Rodney (@infrony) and I like both programming already for me is a hobby. \r\nIn the near future I see myself doing independent projects.',
	public_repos: 8,
	public_gists: 3,
	followers: 1,
	following: 1,
	created_at: '2011-08-26T04:33:24Z',
	updated_at: '2019-05-11T16:41:58Z'
};
